server:
  servlet:
    session:
      timeout: 10m # 10분 후 자동 만료

spring:
  config:
    import:
      - classpath:application-prompts.yaml
  messages:
    encoding: UTF-8

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash

jwt:
  secret: ${JWT_SECRET}
  token-validity: ${JWT_TOKEN_VALIDITY}
