server:
  servlet:
    session:
      timeout: 10m # 10분 후 자동 만료

spring:
  config:
    import:
      - classpath:application-prompts.yaml
  messages:
    encoding: UTF-8

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash

jwt:
  secret: ${JWT_SECRET}
  token-validity: ${JWT_TOKEN_VALIDITY}

logging:
  level:
    root: INFO # 모든 라이브러리(Spring, Hibernate 등) 로그는 INFO 레벨만
    com.fortunehub.luckylog: DEBUG # com.fortunehub.luckylog 패키지의 로그는 DEBUG까지 상세하게
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %logger{36}.%M - %msg%n'
