server:
  servlet:
    session:
      timeout: 10m # 10분 후 자동 만료

spring:
  config:
    import:
      - classpath:application-prompts.yaml
  messages:
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10

logging:
  level:
    root: INFO

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash-lite
